language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t phanhoang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true phanhoang/docker-react npm run test

deploy:
  provider: heroku
  api_key:
    secure: 306d1bb9-be8d-4acc-9435-7a7bc9317682
  app: react-docker-phanhoang
  on:
    branch: master
  